spring:
  cloud:
    gateway:
      routes:
        - id: user_route
          uri: lb://zce-user
          predicates:
            - Path=/api/user/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: test_route
          uri: lb://zce-test
          predicates:
            - Path=/api/test/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: test_article
          uri: lb://zce-article
          predicates:
            - Path=/api/article/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:  # 这段过滤器和验证码有关，api内容缓存了/renren-fast，还得注意/renren-fast也注册到nacos中
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}